// Make constants available globally
window.FASTPATH_INPUT_EVENT_SCANCODE = 0x0;
window.FASTPATH_INPUT_EVENT_MOUSE = 0x1;
window.FASTPATH_INPUT_EVENT_MOUSEX = 0x2;
window.FASTPATH_INPUT_EVENT_SYNC = 0x3;
window.FASTPATH_INPUT_EVENT_UNICODE = 0x4;
window.FASTPATH_INPUT_EVENT_QOE_TIMESTAMP = 0x6;
